[package]
name = "hexx"
version = "0.4.2"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
description = "Hexagonal utilities"
license = "Apache-2.0"
keywords = ["hexagon", "bestagon", "bevy", "geometry"]
categories = ["game-development", "mathematics"]
repository = "https://github.com/ManevilleF/hexx"
exclude = [".github"]

[features]
default = []
# serde compatibility
ser_de = ["serde", "glam/serde"]

[dependencies]
glam = "0.23"
itertools = "0.10"

[dependencies.serde]
version = "1"
default-features = false
features = ["derive"]
optional = true

# For lib.rs doctests and examples
[dev-dependencies.bevy]
version = "0.10"
features = ["bevy_render", "bevy_pbr", "bevy_core_pipeline", "bevy_asset", "bevy_winit", "x11"]
default-features = false

[[example]]
name = "hex_grid"
path = "examples/hex_grid.rs"

[[example]]
name = "3d_columns"
path = "examples/3d_columns.rs"

[profile.dev]
opt-level = 1
