name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # CI builds from scratch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: build
        run: cargo build --verbose

  examples:
    needs: [build, fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: build examples
        run: cargo build --examples --verbose

  tests:
    needs: [build, fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --tests --all-features

  doctest:
    needs: [build, fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Run doctests
        run: cargo test --doc --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    needs: [build, fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo clippy installation
        run: rustup component add clippy
      - name: Run clippy default check
        run: cargo clippy --all --tests -- -D warnings
      - name: Run clippy all features check
        run: cargo clippy --all-features --all --tests -- -D warnings

  rustdoc:
    needs: [build, fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Run rustdoc
        run: cargo rustdoc --all-features -- -D warnings

  checks:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Enforce changelog
        uses: dangoslen/changelog-enforcer@v3
        with:
          missingUpdateErrorMessage: Please add an entry to the CHANGELOG documenting your changes

